In [1]:
import numpy as np
import pandas as pd
pd.__version__


'1.4.4'

In [20]:
list_1=[1,2,3,4]
list_2=[5,6,7,8,9]
list_1.extend(list_2)
list_1

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [4]:
v = np.array([1,2.3]) #This is a scalar

In [3]:
v

array([1. , 2.3])

In [5]:
v=np.array([[1,2,3],[4,5,6]])
v

array([[1, 2, 3],
       [4, 5, 6]])

The following is to practice scalars and vector creation using numpy

In [10]:
import numpy as np

In [5]:
scalar_s = np.array(9)
vector_v = np.array([1,2,3])

In [9]:
type(scalar_s) # this is a scalar with no dimension
type(vector_v) # is a one dimensional vector

numpy.ndarray

The following shows the usage of shape and reshape in vectors

In [20]:
vector_v.shape
vector_v.reshape(3,1)


array([[1],
       [2],
       [3]])

In [30]:
v1 = np.array([[1,2,3],[4,5,6]])
v2 = np.array([[7,8,9],[7,4,1]])


**Tensor**

In [32]:
t = np.array([v1,v2])
t
t.shape
type(t)

numpy.ndarray

***How to create a tensor manually***

In [37]:
tensor_manual = np.array([
    [
        [1,2,3],[4,5,6]
        ],
    [
        [7,8,9],[7,4,1]
        ]
    ])
tensor_manual

array([[[1, 2, 3],
        [4, 5, 6]],

       [[7, 8, 9],
        [7, 4, 1]]])

*addition and subtraction*

In [38]:
v1 + v2

array([[ 8, 10, 12],
       [11,  9,  7]])

In [39]:
v1 - v2

array([[-6, -6, -6],
       [-3,  1,  5]])

In [42]:
v1 * 2

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [43]:
v1.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [50]:
u = np.array([1,2,3])
v = np.array([4,5,6])


**The dot product of two vectors will give a scalar**                                                                                                  
**The cross products of tow vectors will give the coresponding vectors**

In [52]:
np.cross(u,v)

array([-3,  6, -3])

*Using Pandas*

In [4]:
import pandas as pd

In [3]:
products = ["A","B","C","D","E",]

In [8]:
products_to_series = pd.Series(products)
type(products_to_series)

pandas.core.series.Series

In [11]:
#checking the pandas library using an integer value
numbers = [1,2,3,4,5,6,7,8,9]
numbers_to_series = pd.Series(numbers)
numbers_to_series

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64


****Contd...****

In [13]:
numbers_to_series[6]

7

In [5]:
start_date_deposits = pd.Series({
    '7/4/2014'   : 2000,
    '1/2/2015'   : 2000,
    '12/8/2012'  : 1000,
    '2/20/2015'  : 2000,
    '10/28/2013' : 2000,
    '4/19/2015'  : 2000,
    '7/4/2016'   : 2000,
    '4/24/2014'  : 2000,
    '9/3/2015'   : 4000,
    '7/25/2016'  : 2000,
    '5/1/2014'   : 2000,
    '3/29/2013'  : 2000,
    '10/3/2014'  : 2000,
    '9/18/2015'  : 2500
})

In [6]:
start_date_deposits

7/4/2014      2000
1/2/2015      2000
12/8/2012     1000
2/20/2015     2000
10/28/2013    2000
4/19/2015     2000
7/4/2016      2000
4/24/2014     2000
9/3/2015      4000
7/25/2016     2000
5/1/2014      2000
3/29/2013     2000
10/3/2014     2000
9/18/2015     2500
dtype: int64

In [8]:
start_date_deposits.argmax()

8

In [12]:
s = pd.Series(np.random.randn(5), index=["a", "b", "c", "d", "e"])
s

a    0.671903
b   -1.039597
c    0.036664
d    0.011330
e    1.157155
dtype: float64

In [15]:
s['a']#this is using user assigned indexing
s[0]#this is  using default indexing

0.6719027284292151

In [23]:
d = {"b": 1, "a": 0, "c": 2}
d = pd.Series(d)
d.dtype

dtype('int64')

*****Practicing DataFrames*****

In [31]:
data = {"ProductName":['product A','product B','product C','Product D'], "ProductPrice":[242432,234242,456445, None]}
data_index = ['A','B','C','D']
df = pd.DataFrame(data=data, index=data_index)
df

ProductName  ProductPrice
A   product A      242432.0
B   product B      234242.0
C   product C      456445.0
D   Product D           NaN

Creating data frame using a nested list which sometime can cause consistency issues to our data.

In [38]:
product_data= [['product A',2423],
               ['Product B', 3242],
               ['Product C', [4353, 4354]]]#there will be a consistency problem
df = pd.DataFrame(product_data)
df

0             1
0  product A          2423
1  Product B          3242
2  Product C  [4353, 4354]

****This method is used to create data frames using series****

In [68]:
first = pd.Series(['product A', 'product B', 'product C','product D'], index=[1,2,3,4])
second = pd.Series([87657, 76576, 687867], index=[1,2,3])
df = pd.DataFrame({
    'ProductName':first,
    'PoductPrice':second
})
df


ProductName  PoductPrice
1   product A      87657.0
2   product B      76576.0
3   product C     687867.0
4   product D          NaN